name: Spring Boot CI/CD (Gradle → EC2) v1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission to Gradle
      run: chmod +x gradlew

    - name: Build Spring Boot App
      run: ./gradlew clean build

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.ec2-3-237-40-12.compute-1.amazonaws.com }}
        username: ${{ secrets.ec2-user }}
        key: ${{ secrets.EC2_KEY }}
        source: "build/libs/*.jar"
        target: "/home/ec2-user/app"

    - name: Run Spring Boot App
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.ec2-3-237-40-12.compute-1.amazonaws.com }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          pkill -f java || true
          nohup java -jar /home/ec2-user/app/*.jar > app.log 2>&1 &
